---
name: Chicora
layers:
  - |
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x            bb               bb               x
    x            bb             bb                 x    
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x
    x                                              x    
    xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
tileFile: ./tiles.png
tiles:
  " ": 0,0
  "x": 1,1
  "b": 1,1
