---
name: Chicora
layers:
  - |
    xxxxxxxxxxxxxxxxxxxx
    x                  x
    x                  x
    x                  x
    x                  x
    x                  x
    x                  x
    x                  x
    x                  x
    x                  x
    x                  x    
    x                  x
    x                  x
    x                  x
    xxxxxxxxxxxxxxxxxxxx
  - |
    fttttttttttttttttttc
    l                  r
    l                  r
    l                  r
    l                  r
    l                  r
    l                  r
    l   q          q   r
    l                  r
    l                  r
    l                  r    
    l                  r
    l                  r
    l                  r
    ebbbbbbbbbbbbbbbbbbd     
tileFile: world/tiles.png
tiles:
  " ": 0,0
  "x": 4,7
  "q": 2,14
  "r": 2,7
  "l": 4,7
  "t": 3,8
  "b": 3,6
  "c": 3,9
  "d": 3,10
  "e": 2,10
  "f": 2,9