---
name: Chicora
layers:
  - |
    xxxxxxxxxxxxxxxxxxxxxxx
    x                     x
    x                     x
    x                     x
    x    b     x     b    x
    x                     x
    x                     x
    x                     x
    xxxxxxxxxxxxxxxxxxxxxxx
tileFile: ./tiles.png
tiles:
  " ": 6,6
  "x": 5,5
  "b": 3,3
